# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DrinksBottles(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DrinksBottles()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDrinksBottles(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DrinksBottles
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DrinksBottles
    def Sprite(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DrinksBottles
    def Gingerale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DrinksBottles
    def Water(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def DrinksBottlesStart(builder):
    builder.StartObject(3)

def Start(builder):
    DrinksBottlesStart(builder)

def DrinksBottlesAddSprite(builder, sprite):
    builder.PrependInt32Slot(0, sprite, 0)

def AddSprite(builder, sprite):
    DrinksBottlesAddSprite(builder, sprite)

def DrinksBottlesAddGingerale(builder, gingerale):
    builder.PrependInt32Slot(1, gingerale, 0)

def AddGingerale(builder, gingerale):
    DrinksBottlesAddGingerale(builder, gingerale)

def DrinksBottlesAddWater(builder, water):
    builder.PrependInt32Slot(2, water, 0)

def AddWater(builder, water):
    DrinksBottlesAddWater(builder, water)

def DrinksBottlesEnd(builder):
    return builder.EndObject()

def End(builder):
    return DrinksBottlesEnd(builder)
