# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DrinksCans(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DrinksCans()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDrinksCans(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DrinksCans
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DrinksCans
    def Coke(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DrinksCans
    def Beer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DrinksCans
    def Lemonade(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def DrinksCansStart(builder):
    builder.StartObject(3)

def Start(builder):
    DrinksCansStart(builder)

def DrinksCansAddCoke(builder, coke):
    builder.PrependInt32Slot(0, coke, 0)

def AddCoke(builder, coke):
    DrinksCansAddCoke(builder, coke)

def DrinksCansAddBeer(builder, beer):
    builder.PrependInt32Slot(1, beer, 0)

def AddBeer(builder, beer):
    DrinksCansAddBeer(builder, beer)

def DrinksCansAddLemonade(builder, lemonade):
    builder.PrependInt32Slot(2, lemonade, 0)

def AddLemonade(builder, lemonade):
    DrinksCansAddLemonade(builder, lemonade)

def DrinksCansEnd(builder):
    return builder.EndObject()

def End(builder):
    return DrinksCansEnd(builder)
