# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Order(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Order()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOrder(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Order
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Order
    def Veggies(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from CustomAppProto.Veggies import Veggies
            obj = Veggies()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Order
    def Drinks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from CustomAppProto.Drinks import Drinks
            obj = Drinks()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Order
    def Milk(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CustomAppProto.Milk import Milk
            obj = Milk()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Order
    def MilkLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Order
    def MilkIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Order
    def Bread(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CustomAppProto.Bread import Bread
            obj = Bread()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Order
    def BreadLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Order
    def BreadIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Order
    def Meat(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CustomAppProto.Meat import Meat
            obj = Meat()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Order
    def MeatLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Order
    def MeatIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def OrderStart(builder):
    builder.StartObject(5)

def Start(builder):
    OrderStart(builder)

def OrderAddVeggies(builder, veggies):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(veggies), 0)

def AddVeggies(builder, veggies):
    OrderAddVeggies(builder, veggies)

def OrderAddDrinks(builder, drinks):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(drinks), 0)

def AddDrinks(builder, drinks):
    OrderAddDrinks(builder, drinks)

def OrderAddMilk(builder, milk):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(milk), 0)

def AddMilk(builder, milk):
    OrderAddMilk(builder, milk)

def OrderStartMilkVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMilkVector(builder, numElems: int) -> int:
    return OrderStartMilkVector(builder, numElems)

def OrderAddBread(builder, bread):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(bread), 0)

def AddBread(builder, bread):
    OrderAddBread(builder, bread)

def OrderStartBreadVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBreadVector(builder, numElems: int) -> int:
    return OrderStartBreadVector(builder, numElems)

def OrderAddMeat(builder, meat):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(meat), 0)

def AddMeat(builder, meat):
    OrderAddMeat(builder, meat)

def OrderStartMeatVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMeatVector(builder, numElems: int) -> int:
    return OrderStartMeatVector(builder, numElems)

def OrderEnd(builder):
    return builder.EndObject()

def End(builder):
    return OrderEnd(builder)
